# Generated by Django 5.2.13 on 2026-05-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_property_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case created'), ('status_changed', 'Status changed'), ('professional_assigned', 'Professional assigned'), ('troubleshooting_started', 'Troubleshooting started'), ('troubleshooting_progress', 'Troubleshooting progress'), ('ai_diagnostic_progress', 'AI diagnostic progress'), ('note_added', 'Note added'), ('appointment_created', 'Appointment created'), ('appointment_status_changed', 'Appointment status changed')], max_length=64),
        ),
    ]
