# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def build_personal_organization_name(user):
    display_name = " ".join(part for part in (user.first_name, user.last_name) if part).strip()
    if display_name:
        return display_name
    return user.email or f"Utente {user.pk}"


def get_or_create_personal_organization(apps, user):
    organization_plan = apps.get_model("organizations", "OrganizationPlan")
    organization = apps.get_model("organizations", "Organization")
    organization_membership = apps.get_model("organizations", "OrganizationMembership")

    plan, _created = organization_plan.objects.get_or_create(
        slug="personal",
        defaults={
            "name": "Personal",
            "kind": "personal",
            "max_members": 1,
            "can_open_cases": True,
            "can_manage_properties": True,
            "can_share_cases": True,
            "can_receive_cases": False,
            "can_accept_case_requests": False,
            "can_manage_members": False,
            "can_manage_billing": False,
            "can_view_all_org_cases": True,
            "can_use_ai_diagnostics": True,
            "is_active": True,
        },
    )
    org, _created = organization.objects.get_or_create(
        personal_owner_id=user.id,
        defaults={
            "name": build_personal_organization_name(user),
            "kind": "personal",
            "plan": plan,
            "status": "active",
            "created_by_user_id": user.id,
        },
    )
    organization_membership.objects.get_or_create(
        user_id=user.id,
        organization=org,
        defaults={
            "role": "owner",
            "scope": "organization",
            "status": "active",
            "approved_by_user_id": user.id,
            "approved_at": timezone.now(),
        },
    )
    return org


def populate_owner_organizations(apps, _schema_editor):
    property_model = apps.get_model("cases", "Property")
    case_model = apps.get_model("cases", "Case")

    for property_obj in property_model.objects.select_related("owner_user").filter(organization__isnull=True).iterator():
        property_obj.organization = get_or_create_personal_organization(apps, property_obj.owner_user)
        property_obj.save(update_fields=["organization"])

    for case in case_model.objects.select_related("customer_user", "property").filter(owner_organization__isnull=True).iterator():
        if case.property_id and case.property.organization_id:
            case.owner_organization_id = case.property.organization_id
        else:
            case.owner_organization = get_or_create_personal_organization(apps, case.customer_user)
        case.save(update_fields=["owner_organization"])


def reverse_populate_owner_organizations(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_alter_caseevent_event_type"),
        ("organizations", "0002_seed_builtin_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="owner_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="organizations.organization",
            ),
        ),
        migrations.RunPython(populate_owner_organizations, reverse_populate_owner_organizations),
        migrations.AlterField(
            model_name="property",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="owner_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="organizations.organization",
            ),
        ),
    ]

