# Generated by Django 5.2.13 on 2026-05-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_organization_ownership'),
        ('organizations', '0002_seed_builtin_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case created'), ('status_changed', 'Status changed'), ('professional_assigned', 'Professional assigned'), ('troubleshooting_started', 'Troubleshooting started'), ('troubleshooting_progress', 'Troubleshooting progress'), ('ai_diagnostic_progress', 'AI diagnostic progress'), ('note_added', 'Note added'), ('appointment_created', 'Appointment created'), ('appointment_status_changed', 'Appointment status changed'), ('case_share_request_created', 'Case share request created'), ('case_share_request_accepted', 'Case share request accepted'), ('case_share_request_rejected', 'Case share request rejected'), ('case_share_request_revoked', 'Case share request revoked')], max_length=64),
        ),
        migrations.CreateModel(
            name='CaseShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=32)),
                ('share_scope', models.CharField(choices=[('summary', 'Summary'), ('diagnostic_chat', 'Diagnostic chat'), ('selected_attachments', 'Selected attachments'), ('full_case', 'Full case')], default='summary', max_length=32)),
                ('visible_title', models.CharField(max_length=200)),
                ('visible_summary', models.TextField(blank=True)),
                ('shared_payload_json', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_case_share_requests', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='cases.case')),
                ('recipient_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_case_share_requests', to='organizations.organizationmembership')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_case_share_requests', to='organizations.organization')),
                ('rejected_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_case_share_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_share_requests', to=settings.AUTH_USER_MODEL)),
                ('revoked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_case_share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['case', 'status'], name='case_share_case_status_idx'), models.Index(fields=['recipient_organization', 'status'], name='case_share_org_status_idx'), models.Index(fields=['recipient_membership', 'status'], name='case_share_member_status_idx')],
            },
        ),
    ]
