# Generated by Django 5.2.13 on 2026-05-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_caseevent_event_type_casesharerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase'), ('cleaning', 'Cleaning'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('note', 'Note'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='cases.asset')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='cases.property')),
            ],
            options={
                'ordering': ('-event_date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['asset', 'event_date'], name='asset_event_asset_date_idx'), models.Index(fields=['property', 'event_date'], name='asset_event_prop_date_idx'), models.Index(fields=['event_type'], name='asset_event_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(asset__isnull=False) | models.Q(property__isnull=False), name='asset_event_requires_context')],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('recurrence_rule', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual'), ('custom', 'Custom')], default='none', max_length=32)),
                ('recurrence_custom', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='cases.asset')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_reminders', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='cases.property')),
            ],
            options={
                'ordering': ('status', 'due_at', 'id'),
                'indexes': [models.Index(fields=['asset', 'status', 'due_at'], name='asset_rem_asset_status_due_idx'), models.Index(fields=['property', 'status', 'due_at'], name='asset_rem_prop_status_due_idx'), models.Index(fields=['status', 'due_at'], name='asset_rem_status_due_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(asset__isnull=False) | models.Q(property__isnull=False), name='asset_reminder_requires_context')],
            },
        ),
    ]
