# Generated by Django 5.2.13 on 2026-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16),
        ),
    ]
