# Generated by Django 5.2.13 on 2026-05-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_aimessage_error_detail_aimessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AiDiagnosticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='unknown', max_length=16)),
                ('next_question', models.TextField(blank=True)),
                ('escalation_recommended', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('facts_json', models.JSONField(blank=True, default=dict)),
                ('safety_notes_json', models.JSONField(blank=True, default=list)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_snapshot', to='ai_assistant.aisession')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_snapshots', to='ai_assistant.aimessage')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
