# Generated by Django 5.2.13 on 2026-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aimessage_metadata_json_aidiagnosticsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='asked_questions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='compacted_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='context_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='context_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
