# Generated by Django 5.2.13 on 2026-05-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aidiagnosticsnapshot_asked_questions_json_and_more'),
        ('troubleshooting', '0002_diagnosticchapter_diagnosticsafetyrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='diagnostic_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_diagnostic_snapshots', to='troubleshooting.diagnosticchapter'),
        ),
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='diagnostic_chapter_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_diagnostic_snapshots', to='troubleshooting.diagnosticchapteroption'),
        ),
        migrations.AddField(
            model_name='aidiagnosticsnapshot',
            name='excluded_facts_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
