# Generated by Django 5.2.13 on 2026-05-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_aidiagnosticsnapshot_diagnostic_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiContextDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='unknown', max_length=16)),
                ('facts_json', models.JSONField(blank=True, default=dict)),
                ('excluded_facts_json', models.JSONField(blank=True, default=dict)),
                ('asked_questions_json', models.JSONField(blank=True, default=list)),
                ('safety_notes_json', models.JSONField(blank=True, default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('total_completed_messages', models.PositiveIntegerField(default=0)),
                ('estimated_input_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('trigger_reason', models.CharField(blank=True, max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_digests_from', to='ai_assistant.aimessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_digests', to='ai_assistant.aisession')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_digests', to='ai_assistant.aidiagnosticsnapshot')),
                ('to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_digests_to', to='ai_assistant.aimessage')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
