# Generated by Django 5.2.13 on 2026-05-09 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_aiusageledger'),
        ('cases', '0007_assetmaintenanceevent_assetmaintenancereminder'),
        ('guests', '0001_initial'),
        ('organizations', '0003_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisession',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='guests.guestsession'),
        ),
        migrations.AddField(
            model_name='aiusageledger',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_ledger', to='guests.guestsession'),
        ),
        migrations.AlterField(
            model_name='aisession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiusageledger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusageledger',
            index=models.Index(fields=['guest_session', 'created_at'], name='ai_usage_guest_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aisession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_session__isnull', True)), models.Q(('user__isnull', True), ('guest_session__isnull', False)), _connector='OR'), name='ai_session_requires_user_or_guest'),
        ),
    ]
