# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("professional", "Professional"),
                            ("managed", "Managed"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=32,
                    ),
                ),
                ("max_members", models.PositiveIntegerField(default=1)),
                ("can_open_cases", models.BooleanField(default=False)),
                ("can_manage_properties", models.BooleanField(default=False)),
                ("can_share_cases", models.BooleanField(default=False)),
                ("can_receive_cases", models.BooleanField(default=False)),
                ("can_accept_case_requests", models.BooleanField(default=False)),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_manage_billing", models.BooleanField(default=False)),
                ("can_view_all_org_cases", models.BooleanField(default=False)),
                ("can_use_ai_diagnostics", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("professional", "Professional"),
                            ("managed", "Managed"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived")],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "personal_owner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_organization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="organizations.organizationplan",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("administrative", "Administrative"),
                            ("technician", "Technician"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("organization", "Organization"), ("assigned", "Assigned")],
                        default="assigned",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("organization__name", "user__email", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["kind", "status"], name="org_kind_status_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["organization", "status"], name="org_membership_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["user", "status"], name="org_membership_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["role", "scope"], name="org_membership_role_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(fields=("organization", "user"), name="unique_organization_membership_user"),
        ),
    ]
