# Generated by Codex on 2026-05-09

from django.db import migrations


BUILTIN_PLANS = [
    {
        "slug": "personal",
        "name": "Personal",
        "kind": "personal",
        "max_members": 1,
        "can_open_cases": True,
        "can_manage_properties": True,
        "can_share_cases": True,
        "can_receive_cases": False,
        "can_accept_case_requests": False,
        "can_manage_members": False,
        "can_manage_billing": False,
        "can_view_all_org_cases": True,
        "can_use_ai_diagnostics": True,
        "is_active": True,
    },
    {
        "slug": "professional",
        "name": "Professional",
        "kind": "professional",
        "max_members": 1,
        "can_open_cases": False,
        "can_manage_properties": False,
        "can_share_cases": False,
        "can_receive_cases": True,
        "can_accept_case_requests": True,
        "can_manage_members": True,
        "can_manage_billing": True,
        "can_view_all_org_cases": True,
        "can_use_ai_diagnostics": True,
        "is_active": True,
    },
]


def seed_builtin_plans(apps, _schema_editor):
    organization_plan = apps.get_model("organizations", "OrganizationPlan")
    for plan_data in BUILTIN_PLANS:
        defaults = plan_data.copy()
        slug = defaults.pop("slug")
        organization_plan.objects.update_or_create(slug=slug, defaults=defaults)


def reverse_seed_builtin_plans(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_builtin_plans, reverse_seed_builtin_plans),
    ]

