# Generated by Django 5.2.13 on 2026-04-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_flows', to='taxonomy.category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DiagnosticNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('node_type', models.CharField(choices=[('question', 'Question'), ('solution', 'Solution'), ('warning', 'Warning'), ('escalation', 'Escalation')], max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_entrypoint', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='troubleshooting.diagnosticflow')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiagnosticOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='troubleshooting.diagnosticnode')),
                ('to_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_options', to='troubleshooting.diagnosticnode')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
