# Generated by Django 5.2.13 on 2026-05-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_context', models.TextField(blank=True)),
                ('safety_context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_chapters', to='taxonomy.category')),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('trigger_terms_json', models.JSONField(blank=True, default=list)),
                ('guidance', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='unknown', max_length=16)),
                ('escalation_level', models.CharField(choices=[('none', 'None'), ('recommended', 'Recommended'), ('required', 'Required'), ('urgent', 'Urgent')], default='none', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_rules', to='troubleshooting.diagnosticchapter')),
            ],
            options={
                'ordering': ('sort_order', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiagnosticChapterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('option_type', models.CharField(choices=[('asset_type', 'Asset type'), ('symptom', 'Symptom'), ('safety_signal', 'Safety signal'), ('generic', 'Generic')], default='generic', max_length=32)),
                ('prompt_hint', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='troubleshooting.diagnosticchapter')),
            ],
            options={
                'ordering': ('sort_order', 'label', 'id'),
                'constraints': [models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_diagnostic_chapter_option_slug')],
            },
        ),
    ]
