# Generated by Django 5.2.13 on 2026-05-09 07:10

import apps.troubleshooting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshooting', '0002_diagnosticchapter_diagnosticsafetyrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAdviceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('step_type', models.CharField(choices=[('observation', 'Observation'), ('safe_check', 'Safe check'), ('prevention', 'Prevention'), ('escalation', 'Escalation')], default='safe_check', max_length=32)),
                ('safety_level', models.CharField(choices=[('none', 'None'), ('caution', 'Caution'), ('stop', 'Stop')], default='caution', max_length=16)),
                ('resolution_prompt', models.CharField(default='Hai risolto?', max_length=200)),
                ('next_actions_json', models.JSONField(blank=True, default=apps.troubleshooting.models.default_advice_next_actions)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_steps', to='troubleshooting.diagnosticchapter')),
                ('chapter_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advice_steps', to='troubleshooting.diagnosticchapteroption')),
            ],
            options={
                'ordering': ('sort_order', 'title', 'id'),
                'constraints': [models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_diagnostic_advice_step_slug')],
            },
        ),
    ]
