# Generated by Django 5.2.13 on 2026-05-09 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('push_provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification service'), ('web_push', 'Web Push'), ('none', 'None')], default='none', max_length=32)),
                ('push_token', models.CharField(blank=True, max_length=512)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('locale', models.CharField(blank=True, max_length=32)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['user', 'is_active', 'last_seen_at'], name='device_user_active_seen_idx'), models.Index(fields=['push_provider', 'is_active'], name='device_provider_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('case_share_request_created', 'Case share request created'), ('case_share_request_accepted', 'Case share request accepted'), ('case_share_request_rejected', 'Case share request rejected'), ('case_share_request_revoked', 'Case share request revoked'), ('conversation_post_created', 'Conversation post created'), ('appointment_created', 'Appointment created'), ('appointment_status_changed', 'Appointment status changed'), ('maintenance_reminder_due', 'Maintenance reminder due'), ('system', 'System')], max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient_user', 'read_at', 'created_at'], name='notif_rec_read_created_idx'), models.Index(fields=['recipient_user', 'notification_type'], name='notif_rec_type_idx'), models.Index(fields=['target_type', 'target_id'], name='notif_target_idx')],
            },
        ),
    ]
